/**
* Copyright (c) 2003 Sun Microsystems, Inc. All  Rights Reserved.
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions are met:
*
* -Redistribution of source code must retain the above copyright notice, 
* this list of conditions and the following disclaimer.
*
* -Redistribution in binary form must reproduce the above copyright notice, 
* this list of conditions and the following disclaimer in the documentation
* and/or other materials provided with the distribution.
*
* Neither the name of Sun Microsystems, Inc. or the names of contributors may 
* be used to endorse or promote products derived from this software without 
* specific prior written permission.
* 
* This software is provided "AS IS," without a warranty of any kind.
* ALL EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS AND WARRANTIES, INCLUDING
* ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
* NON-INFRINGEMENT, ARE HEREBY EXCLUDED. SUN MIDROSYSTEMS, INC. ("SUN") AND ITS
* LICENSORS SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A
* RESULT OF USING, MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
* IN NO EVENT WILL SUN OR ITS LICENSORS BE LIABLE FOR ANY LOST REVENUE, PROFIT
* OR DATA, OR FOR DIRECT, INDIRECT, SPECIAL, CONSEQUENTIAL, INCIDENTAL OR
* PUNITIVE DAMAGES, HOWEVER CAUSED AND REGARDLESS OF THE THEORY OF LIABILITY,
* ARISING OUT OF THE USE OF OR INABILITY TO USE THIS SOFTWARE, EVEN IF SUN HAS
* BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
*
* You acknowledge that this software is not designed or intended for use in the
* design, construction, operation or maintenance of any nuclear facility.
*/


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_joal_ALImpl */

#ifndef _Included_net_java_games_joal_ALImpl
#define _Included_net_java_games_joal_ALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGenBuffersNative
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGenBuffersNative__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGenBuffersNative
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGenBuffersNative__I_3I
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alDeleteBuffersNative
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alDeleteBuffersNative__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alDeleteBuffersNative
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alDeleteBuffersNative__I_3I
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alIsBuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_games_joal_ALImpl_alIsBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alBufferDataNative
 * Signature: (II[BII)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alBufferDataNative__II_3BII
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alBufferDataNative
 * Signature: (IILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alBufferDataNative__IILjava_nio_ByteBuffer_2II
  (JNIEnv *, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetBufferfNative
 * Signature: (II[F)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetBufferfNative__II_3F
  (JNIEnv *, jobject, jint, jint, jfloatArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetBufferfNative
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetBufferfNative__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetBufferf
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_net_java_games_joal_ALImpl_alGetBufferf
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetBufferiNative
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetBufferiNative__II_3I
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetBufferiNative
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetBufferiNative__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetBufferi
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_joal_ALImpl_alGetBufferi
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGenSourcesNative
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGenSourcesNative__I_3I
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGenSourcesNative
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGenSourcesNative__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alDeleteSourcesNative
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alDeleteSourcesNative__I_3I
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alDeleteSourcesNative
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alDeleteSourcesNative__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alIsSource
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_games_joal_ALImpl_alIsSource
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourcei
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourcei
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourcef
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourcef
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourcefv
 * Signature: (II[F)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourcefv
  (JNIEnv *, jobject, jint, jint, jfloatArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourcefvNative
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourcefvNative
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSource3f
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSource3f
  (JNIEnv *, jobject, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetSourcefNative
 * Signature: (II[F)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetSourcefNative__II_3F
  (JNIEnv *, jobject, jint, jint, jfloatArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetSourcefNative
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetSourcefNative__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetSourcef
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_net_java_games_joal_ALImpl_alGetSourcef
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetSourcefvNative
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetSourcefvNative__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetSourcefvNative
 * Signature: (II[F)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetSourcefvNative__II_3F
  (JNIEnv *, jobject, jint, jint, jfloatArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetSourceiNative
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetSourceiNative__II_3I
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetSourceiNative
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetSourceiNative__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetSourcei
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_joal_ALImpl_alGetSourcei
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourcePlay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourcePlay
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourcePlayvNative
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourcePlayvNative__I_3I
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourcePlayvNative
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourcePlayvNative__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourcePause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourcePause
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourcePausevNative
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourcePausevNative__I_3I
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourcePausevNative
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourcePausevNative__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourceStop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourceStop
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourceStopvNative
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourceStopvNative__I_3I
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourceStopvNative
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourceStopvNative__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourceRewind
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourceRewind
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourceRewindvNative
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourceRewindvNative__I_3I
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourceRewindvNative
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourceRewindvNative__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourceQueueBuffersNative
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourceQueueBuffersNative__II_3I
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourceQueueBuffersNative
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourceQueueBuffersNative__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourceUnqueueBuffersNative
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourceUnqueueBuffersNative__II_3I
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alSourceUnqueueBuffersNative
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alSourceUnqueueBuffersNative__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alListenerf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alListenerf
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alListener3f
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alListener3f
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alListenerfv
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alListenerfv__I_3F
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alListenerfv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alListenerfv__ILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alListeneri
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alListeneri
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetListenerfNative
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetListenerfNative__I_3F
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetListenerfNative
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetListenerfNative__ILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetListenerf
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_net_java_games_joal_ALImpl_alGetListenerf
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetListener3fNative
 * Signature: (ILjava/nio/FloatBuffer;Ljava/nio/FloatBuffer;Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetListener3fNative__ILjava_nio_FloatBuffer_2Ljava_nio_FloatBuffer_2Ljava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jobject, jobject, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetListener3fNative
 * Signature: (I[F[F[F)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetListener3fNative__I_3F_3F_3F
  (JNIEnv *, jobject, jint, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetListenerfvNative
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetListenerfvNative__I_3F
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetListenerfvNative
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetListenerfvNative__ILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetListeneriNative
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetListeneriNative__I_3I
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetListeneriNative
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetListeneriNative__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetListeneri
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_joal_ALImpl_alGetListeneri
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alEnable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alEnable
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alDisable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alDisable
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alIsEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_games_joal_ALImpl_alIsEnabled
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetBoolean
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_games_joal_ALImpl_alGetBoolean
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetDouble
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_net_java_games_joal_ALImpl_alGetDouble
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetFloat
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_net_java_games_joal_ALImpl_alGetFloat
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetInteger
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_joal_ALImpl_alGetInteger
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetDoublevNative
 * Signature: (I[D)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetDoublevNative__I_3D
  (JNIEnv *, jobject, jint, jdoubleArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetDoublevNative
 * Signature: (ILjava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetDoublevNative__ILjava_nio_DoubleBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetFloatvNative
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetFloatvNative__I_3F
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetFloatvNative
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetFloatvNative__ILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetIntegervNative
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetIntegervNative__I_3I
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetIntegervNative
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alGetIntegervNative__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_games_joal_ALImpl_alGetString
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alDistanceModel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alDistanceModel
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alDopplerFactor
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alDopplerFactor
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alDopplerVelocity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_java_games_joal_ALImpl_alDopplerVelocity
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_java_games_joal_ALImpl_alGetError
  (JNIEnv *, jobject);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alIsExtensionPresent
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_games_joal_ALImpl_alIsExtensionPresent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_java_games_joal_ALImpl
 * Method:    alGetEnumValue
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_joal_ALImpl_alGetEnumValue
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
